package by.htp.epam.bonjo.web.command;

public enum CommandNames {

	MAIN_PAGE, LOGIN_PAGE, LOGOUT_PAGE, PROFILE_PAGE, SIGNUP_PAGE,

	CREATE_AD_PAGE, EDIT_AD_PAGE, USER_ADS_PAGE, VIEW_AD_PAGE,

	CREATE_CATEGORY_PAGE, EDIT_CATEGORY_PAGE, EDIT_USERS_PAGE

}
